server:
  port: 8092
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: example-service
          uri: lb://example-service
          predicates:
            - Path=/examples/**
        - id: ms-bootcoin-account
          uri: lb://ms-bootcoin-account
          predicates:
            - Path=/**
        - id: ms-bootcoin-transaction
          uri: lb://ms-bootcoin-transaction
          predicates:
            - Path=/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
